/**
 * emoji-data.ts
 *
 * A curated set of emojis for the Word Editor's "Emoji fallback" field
 * (shown when a word has no SVG/photo) — not the full Unicode emoji set,
 * which is mostly irrelevant to vocabulary words (flags, zodiac signs,
 * keycaps…). Grouped into categories that roughly track the domains
 * words are already tagged with (animals, food, body…), each entry
 * carrying a few search keywords so the picker's search box can find
 * "dog" without the admin having to know it's technically 🐕 not 🐶.
 */

export interface EmojiEntry {
  char: string;
  keywords: string[];
}

export interface EmojiCategory {
  name: string;
  emojis: EmojiEntry[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    name: 'Animals',
    emojis: [
      { char: '🐶', keywords: ['dog', 'puppy'] },
      { char: '🐱', keywords: ['cat', 'kitten'] },
      { char: '🐭', keywords: ['mouse'] },
      { char: '🐹', keywords: ['hamster'] },
      { char: '🐰', keywords: ['rabbit', 'bunny'] },
      { char: '🦊', keywords: ['fox'] },
      { char: '🐻', keywords: ['bear'] },
      { char: '🐼', keywords: ['panda'] },
      { char: '🐨', keywords: ['koala'] },
      { char: '🐯', keywords: ['tiger'] },
      { char: '🦁', keywords: ['lion'] },
      { char: '🐮', keywords: ['cow'] },
      { char: '🐷', keywords: ['pig'] },
      { char: '🐸', keywords: ['frog'] },
      { char: '🐵', keywords: ['monkey'] },
      { char: '🐔', keywords: ['chicken', 'hen'] },
      { char: '🐧', keywords: ['penguin'] },
      { char: '🐦', keywords: ['bird'] },
      { char: '🦅', keywords: ['eagle'] },
      { char: '🦆', keywords: ['duck'] },
      { char: '🦉', keywords: ['owl'] },
      { char: '🐺', keywords: ['wolf'] },
      { char: '🐗', keywords: ['boar'] },
      { char: '🐴', keywords: ['horse'] },
      { char: '🦄', keywords: ['unicorn'] },
      { char: '🐝', keywords: ['bee'] },
      { char: '🐛', keywords: ['caterpillar', 'bug'] },
      { char: '🦋', keywords: ['butterfly'] },
      { char: '🐌', keywords: ['snail'] },
      { char: '🐞', keywords: ['ladybug', 'beetle'] },
      { char: '🐜', keywords: ['ant'] },
      { char: '🕷️', keywords: ['spider'] },
      { char: '🦂', keywords: ['scorpion'] },
      { char: '🐢', keywords: ['turtle'] },
      { char: '🐍', keywords: ['snake'] },
      { char: '🦎', keywords: ['lizard'] },
      { char: '🐙', keywords: ['octopus'] },
      { char: '🦑', keywords: ['squid'] },
      { char: '🦀', keywords: ['crab'] },
      { char: '🐡', keywords: ['pufferfish'] },
      { char: '🐠', keywords: ['fish', 'tropical'] },
      { char: '🐟', keywords: ['fish'] },
      { char: '🐬', keywords: ['dolphin'] },
      { char: '🐳', keywords: ['whale'] },
      { char: '🦈', keywords: ['shark'] },
      { char: '🐊', keywords: ['crocodile', 'alligator'] },
      { char: '🐆', keywords: ['leopard'] },
      { char: '🦓', keywords: ['zebra'] },
      { char: '🦍', keywords: ['gorilla'] },
      { char: '🐘', keywords: ['elephant'] },
      { char: '🦏', keywords: ['rhino'] },
      { char: '🦒', keywords: ['giraffe'] },
      { char: '🐪', keywords: ['camel'] },
      { char: '🦌', keywords: ['deer'] },
      { char: '🐐', keywords: ['goat'] },
      { char: '🐑', keywords: ['sheep'] },
      { char: '🦙', keywords: ['llama', 'alpaca'] },
      { char: '🐿️', keywords: ['squirrel'] },
      { char: '🦔', keywords: ['hedgehog'] },
      { char: '🦇', keywords: ['bat'] },
    ],
  },
  {
    name: 'Food & Drink',
    emojis: [
      { char: '🍎', keywords: ['apple'] },
      { char: '🍊', keywords: ['orange'] },
      { char: '🍋', keywords: ['lemon'] },
      { char: '🍌', keywords: ['banana'] },
      { char: '🍉', keywords: ['watermelon'] },
      { char: '🍇', keywords: ['grapes'] },
      { char: '🍓', keywords: ['strawberry'] },
      { char: '🫐', keywords: ['blueberries'] },
      { char: '🍈', keywords: ['melon'] },
      { char: '🍒', keywords: ['cherries', 'cherry'] },
      { char: '🍑', keywords: ['peach'] },
      { char: '🥭', keywords: ['mango'] },
      { char: '🍍', keywords: ['pineapple'] },
      { char: '🥥', keywords: ['coconut'] },
      { char: '🥝', keywords: ['kiwi'] },
      { char: '🍅', keywords: ['tomato'] },
      { char: '🥑', keywords: ['avocado'] },
      { char: '🥦', keywords: ['broccoli'] },
      { char: '🥬', keywords: ['lettuce', 'leafy green'] },
      { char: '🥒', keywords: ['cucumber'] },
      { char: '🌶️', keywords: ['pepper', 'chili'] },
      { char: '🌽', keywords: ['corn'] },
      { char: '🥕', keywords: ['carrot'] },
      { char: '🧄', keywords: ['garlic'] },
      { char: '🧅', keywords: ['onion'] },
      { char: '🥔', keywords: ['potato'] },
      { char: '🍞', keywords: ['bread'] },
      { char: '🥐', keywords: ['croissant'] },
      { char: '🥖', keywords: ['baguette'] },
      { char: '🧀', keywords: ['cheese'] },
      { char: '🥚', keywords: ['egg'] },
      { char: '🍳', keywords: ['fried egg', 'cooking'] },
      { char: '🥞', keywords: ['pancakes'] },
      { char: '🥓', keywords: ['bacon'] },
      { char: '🍗', keywords: ['chicken leg', 'poultry'] },
      { char: '🍖', keywords: ['meat', 'bone'] },
      { char: '🌭', keywords: ['hot dog'] },
      { char: '🍔', keywords: ['hamburger', 'burger'] },
      { char: '🍟', keywords: ['fries'] },
      { char: '🍕', keywords: ['pizza'] },
      { char: '🌮', keywords: ['taco'] },
      { char: '🌯', keywords: ['burrito'] },
      { char: '🥗', keywords: ['salad'] },
      { char: '🍝', keywords: ['pasta', 'spaghetti'] },
      { char: '🍜', keywords: ['noodles', 'ramen'] },
      { char: '🍲', keywords: ['stew', 'soup'] },
      { char: '🍣', keywords: ['sushi'] },
      { char: '🍤', keywords: ['shrimp', 'fried'] },
      { char: '🍚', keywords: ['rice'] },
      { char: '🍦', keywords: ['ice cream', 'soft serve'] },
      { char: '🍩', keywords: ['donut'] },
      { char: '🍪', keywords: ['cookie'] },
      { char: '🎂', keywords: ['cake', 'birthday'] },
      { char: '🍰', keywords: ['cake', 'slice'] },
      { char: '🍫', keywords: ['chocolate'] },
      { char: '🍬', keywords: ['candy'] },
      { char: '🍯', keywords: ['honey'] },
      { char: '☕', keywords: ['coffee'] },
      { char: '🍵', keywords: ['tea'] },
      { char: '🥤', keywords: ['drink', 'soda'] },
      { char: '🧃', keywords: ['juice box'] },
      { char: '🍷', keywords: ['wine'] },
      { char: '🍺', keywords: ['beer'] },
      { char: '🥛', keywords: ['milk'] },
      { char: '🧊', keywords: ['ice'] },
    ],
  },
  {
    name: 'Nature & Weather',
    emojis: [
      { char: '🌳', keywords: ['tree'] },
      { char: '🌲', keywords: ['pine', 'evergreen'] },
      { char: '🌴', keywords: ['palm tree'] },
      { char: '🌵', keywords: ['cactus'] },
      { char: '🌱', keywords: ['seedling', 'plant'] },
      { char: '🌿', keywords: ['herb'] },
      { char: '☘️', keywords: ['shamrock', 'clover'] },
      { char: '🍀', keywords: ['clover', 'luck'] },
      { char: '🍁', keywords: ['maple leaf', 'autumn'] },
      { char: '🍂', keywords: ['fallen leaf'] },
      { char: '🌾', keywords: ['wheat'] },
      { char: '🌷', keywords: ['tulip', 'flower'] },
      { char: '🌹', keywords: ['rose'] },
      { char: '🌻', keywords: ['sunflower'] },
      { char: '🌼', keywords: ['flower', 'daisy'] },
      { char: '🌸', keywords: ['blossom', 'flower'] },
      { char: '💐', keywords: ['bouquet'] },
      { char: '🍄', keywords: ['mushroom'] },
      { char: '🌊', keywords: ['wave', 'ocean'] },
      { char: '🏔️', keywords: ['mountain'] },
      { char: '⛰️', keywords: ['mountain'] },
      { char: '🌋', keywords: ['volcano'] },
      { char: '🏖️', keywords: ['beach'] },
      { char: '🏜️', keywords: ['desert'] },
      { char: '🌅', keywords: ['sunrise'] },
      { char: '🌄', keywords: ['sunrise', 'mountains'] },
      { char: '🌆', keywords: ['city', 'dusk'] },
      { char: '🌌', keywords: ['stars', 'galaxy', 'night sky'] },
      { char: '☀️', keywords: ['sun'] },
      { char: '🌙', keywords: ['moon'] },
      { char: '⭐', keywords: ['star'] },
      { char: '☁️', keywords: ['cloud'] },
      { char: '⛅', keywords: ['partly cloudy'] },
      { char: '🌧️', keywords: ['rain'] },
      { char: '⛈️', keywords: ['thunderstorm'] },
      { char: '❄️', keywords: ['snowflake', 'snow'] },
      { char: '☃️', keywords: ['snowman'] },
      { char: '🌈', keywords: ['rainbow'] },
      { char: '💧', keywords: ['droplet', 'water'] },
      { char: '🔥', keywords: ['fire'] },
      { char: '🌍', keywords: ['earth', 'globe', 'world'] },
    ],
  },
  {
    name: 'Body & People',
    emojis: [
      { char: '👶', keywords: ['baby'] },
      { char: '🧒', keywords: ['child'] },
      { char: '👦', keywords: ['boy'] },
      { char: '👧', keywords: ['girl'] },
      { char: '👨', keywords: ['man'] },
      { char: '👩', keywords: ['woman'] },
      { char: '🧑', keywords: ['person'] },
      { char: '👴', keywords: ['old man', 'grandfather'] },
      { char: '👵', keywords: ['old woman', 'grandmother'] },
      { char: '👪', keywords: ['family'] },
      { char: '👀', keywords: ['eyes'] },
      { char: '👁️', keywords: ['eye'] },
      { char: '👃', keywords: ['nose'] },
      { char: '👂', keywords: ['ear'] },
      { char: '👄', keywords: ['mouth', 'lips'] },
      { char: '🦷', keywords: ['tooth', 'teeth'] },
      { char: '👅', keywords: ['tongue'] },
      { char: '💪', keywords: ['arm', 'muscle', 'strong'] },
      { char: '🦵', keywords: ['leg'] },
      { char: '🦶', keywords: ['foot'] },
      { char: '✋', keywords: ['hand'] },
      { char: '👆', keywords: ['finger', 'point up'] },
      { char: '🫀', keywords: ['heart', 'organ'] },
      { char: '🧠', keywords: ['brain'] },
      { char: '💀', keywords: ['skull'] },
      { char: '🦴', keywords: ['bone'] },
      { char: '❤️', keywords: ['heart', 'love'] },
      { char: '😀', keywords: ['smile', 'happy'] },
      { char: '😢', keywords: ['sad', 'crying'] },
      { char: '😡', keywords: ['angry'] },
      { char: '😱', keywords: ['scared', 'shocked'] },
      { char: '😴', keywords: ['sleep', 'tired'] },
      { char: '😍', keywords: ['love', 'heart eyes'] },
      { char: '🤔', keywords: ['thinking'] },
      { char: '😂', keywords: ['laughing'] },
    ],
  },
  {
    name: 'Objects & Home',
    emojis: [
      { char: '🏠', keywords: ['house', 'home'] },
      { char: '🏢', keywords: ['building', 'office'] },
      { char: '🏫', keywords: ['school'] },
      { char: '🏥', keywords: ['hospital'] },
      { char: '🏦', keywords: ['bank'] },
      { char: '⛪', keywords: ['church'] },
      { char: '🚪', keywords: ['door'] },
      { char: '🪑', keywords: ['chair'] },
      { char: '🛏️', keywords: ['bed'] },
      { char: '🛋️', keywords: ['couch', 'sofa'] },
      { char: '🚿', keywords: ['shower'] },
      { char: '🛁', keywords: ['bathtub', 'bath'] },
      { char: '🪞', keywords: ['mirror'] },
      { char: '🪟', keywords: ['window'] },
      { char: '🔑', keywords: ['key'] },
      { char: '🔒', keywords: ['lock', 'locked'] },
      { char: '💡', keywords: ['light bulb', 'idea'] },
      { char: '🕯️', keywords: ['candle'] },
      { char: '📱', keywords: ['phone', 'cell phone'] },
      { char: '💻', keywords: ['laptop', 'computer'] },
      { char: '⌚', keywords: ['watch', 'clock'] },
      { char: '📷', keywords: ['camera'] },
      { char: '📺', keywords: ['television', 'tv'] },
      { char: '📻', keywords: ['radio'] },
      { char: '🔋', keywords: ['battery'] },
      { char: '💰', keywords: ['money', 'bag'] },
      { char: '💵', keywords: ['money', 'dollar', 'bill'] },
      { char: '💳', keywords: ['credit card'] },
      { char: '📖', keywords: ['book', 'open book'] },
      { char: '📚', keywords: ['books'] },
      { char: '✏️', keywords: ['pencil'] },
      { char: '🖊️', keywords: ['pen'] },
      { char: '📝', keywords: ['note', 'memo'] },
      { char: '✂️', keywords: ['scissors'] },
      { char: '📌', keywords: ['pin'] },
      { char: '📦', keywords: ['box', 'package'] },
      { char: '🎁', keywords: ['gift', 'present'] },
      { char: '⚽', keywords: ['soccer', 'football', 'ball'] },
      { char: '🏀', keywords: ['basketball'] },
      { char: '🎸', keywords: ['guitar'] },
      { char: '🎹', keywords: ['piano', 'keyboard'] },
      { char: '🎨', keywords: ['art', 'palette', 'painting'] },
      { char: '🧸', keywords: ['teddy bear', 'toy'] },
      { char: '🎈', keywords: ['balloon'] },
      { char: '⏰', keywords: ['alarm clock'] },
      { char: '🧴', keywords: ['bottle', 'lotion'] },
      { char: '🧺', keywords: ['basket'] },
      { char: '🗑️', keywords: ['trash', 'garbage'] },
      { char: '🔨', keywords: ['hammer', 'tool'] },
      { char: '🪒', keywords: ['razor'] },
      { char: '🧹', keywords: ['broom'] },
      { char: '🧷', keywords: ['safety pin'] },
      { char: '👓', keywords: ['glasses'] },
      { char: '👑', keywords: ['crown'] },
      { char: '💍', keywords: ['ring'] },
      { char: '🎒', keywords: ['backpack'] },
      { char: '👜', keywords: ['purse', 'handbag'] },
      { char: '👕', keywords: ['shirt'] },
      { char: '👖', keywords: ['pants', 'jeans'] },
      { char: '👗', keywords: ['dress'] },
      { char: '👠', keywords: ['heel', 'shoe'] },
      { char: '👟', keywords: ['shoe', 'sneaker'] },
      { char: '🧦', keywords: ['sock'] },
      { char: '🧢', keywords: ['cap', 'hat'] },
      { char: '🧥', keywords: ['coat', 'jacket'] },
      { char: '☂️', keywords: ['umbrella'] },
    ],
  },
  {
    name: 'Transport & Places',
    emojis: [
      { char: '🚗', keywords: ['car'] },
      { char: '🚕', keywords: ['taxi'] },
      { char: '🚌', keywords: ['bus'] },
      { char: '🚓', keywords: ['police car'] },
      { char: '🚑', keywords: ['ambulance'] },
      { char: '🚒', keywords: ['fire truck'] },
      { char: '🚚', keywords: ['truck'] },
      { char: '🚲', keywords: ['bicycle', 'bike'] },
      { char: '🏍️', keywords: ['motorcycle'] },
      { char: '✈️', keywords: ['airplane', 'plane'] },
      { char: '🚁', keywords: ['helicopter'] },
      { char: '🚂', keywords: ['train'] },
      { char: '🚆', keywords: ['train'] },
      { char: '🚇', keywords: ['subway', 'metro'] },
      { char: '⛵', keywords: ['sailboat', 'boat'] },
      { char: '🚢', keywords: ['ship'] },
      { char: '⚓', keywords: ['anchor'] },
      { char: '🚦', keywords: ['traffic light'] },
      { char: '🛣️', keywords: ['road', 'highway'] },
      { char: '🗺️', keywords: ['map'] },
      { char: '🧭', keywords: ['compass'] },
    ],
  },
];

/** Every emoji flattened, for the search box's "match against all
 *  categories at once" mode. */
export const ALL_EMOJIS: EmojiEntry[] = EMOJI_CATEGORIES.flatMap(c => c.emojis);
